# -*- coding: utf-8 -*-
"""Final_Capstone_Project_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10D-zdde-zaQgX6NYFH-C2NSHnPGOEZpq
"""

pip install category_encoders

from google.colab import drive
import pandas as pd
from imblearn.over_sampling import RandomOverSampler
import numpy as np
import shap
from sklearn.model_selection import learning_curve
import seaborn as sns
import pickle
from sklearn.metrics import PrecisionRecallDisplay, average_precision_score, precision_score, recall_score
from sklearn.model_selection import RandomizedSearchCV, StratifiedKFold
import matplotlib.pyplot as plt
from scipy.stats import normaltest
from sklearn.metrics import RocCurveDisplay, roc_auc_score
from sklearn.impute import KNNImputer
from xgboost import XGBClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer, SimpleImputer, KNNImputer
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split, \
                                    learning_curve, \
                                    GridSearchCV, cross_validate,cross_val_score, RandomizedSearchCV, StratifiedKFold,cross_val_predict
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from category_encoders import BinaryEncoder
from sklearn.metrics import classification_report, confusion_matrix, precision_recall_curve, make_scorer, fbeta_score, precision_score, recall_score, accuracy_score
from imblearn.pipeline import Pipeline as ImbPipeline
from imblearn.pipeline import Pipeline
from imblearn.over_sampling import SMOTE
from imblearn.combine import SMOTEENN, SMOTETomek
from sklearn.ensemble import VotingClassifier
from scipy.stats import mannwhitneyu
from scipy.stats import chi2_contingency
from sklearn.preprocessing import StandardScaler,  MinMaxScaler, RobustScaler
import warnings
warnings.filterwarnings('ignore')

drive.mount('/content/drive')
path = '/content/drive/MyDrive/Dataset Capstone 3/data_train_95.csv'
df = pd.read_csv(path)

"""#Explanatory Data Analysis"""

df.shape

df.info()

df.head()

df.describe()

"""Check the Distribution of Categorical and Numerical Data


"""

df.hist(figsize=(15,10))

df['PreferedOrderCat'].unique() #6

df['PreferedOrderCat'] = df['PreferedOrderCat'].replace({'Mobile': 'Mobile Phone'})

df['PreferedOrderCat'].value_counts()

df['MaritalStatus'].unique() #3

df['MaritalStatus'].value_counts()

"""Handling Data Duplicate"""

df.duplicated().sum()

#Hapus Duplikasi
duplicated_rows = df[df.duplicated(keep=False)].sort_values(by=df.columns.tolist())
display(duplicated_rows)

dup_summary = (df.groupby(df.columns.tolist(), dropna=False).size().value_counts())
print(dup_summary)

df = df.drop_duplicates()
df.shape

"""Data Visualisation"""

#Churn Overview
df['Churn'].value_counts().plot.pie(labels=['Active','Churn'], autopct='%1.1f%%')
plt.title('Distribusi Churn')
plt.legend()
plt.ylabel('')

#Complain vs Churn Rate
sns.barplot(x='Complain', y='Churn', data=df)
plt.xticks([0,1], ['Active', 'Complain'])
plt.title('Churn Rate Berdasarkan Complain')

#Tenure Segment vs Churn Rate
tenure_segment= pd.cut(df['Tenure'], bins=[-1, 3, 12, 100],
                              labels=['New', 'Mid', 'Loyal'])
sns.barplot(x=tenure_segment, y='Churn', data=df)
plt.title('Churn Rate Berdasarkan Tenure Segment')

#Distribusi Cashback Amount Berdasarkan Churn
sns.histplot(data=df, x='CashbackAmount', hue='Churn', kde=True)
plt.title('Distribusi Cashback Amount (Active vs Churn)')

"""Handling Missing Values"""

df.isnull().sum()

df[['Tenure', 'WarehouseToHome', 'DaySinceLastOrder']].describe()

"""Check Outliers"""

df.boxplot(figsize = (20,6))
plt.show()

df['WarehouseToHome'].value_counts()

outlier = df[df['WarehouseToHome'] == 127.0]
df = df.drop(index=outlier.index)

df[df['CashbackAmount'] > 270]['Churn'].mean()

"""Heatmap Spearman Correlation"""

df_num = df.select_dtypes(include='number')
corr = df_num.corr(method='spearman')
plt.figure(figsize=(10,7))
sns.heatmap(corr, annot=True, cmap='coolwarm', fmt='.2f', linewidths=0.5)
plt.title('Heatmap Korelasi')
plt.show()

"""Features Statistical Test


*   Categorical: Chi-Square
*   Numerical: Man-Whitney


"""

cat_cols = df.select_dtypes(include='object').columns.tolist()

#Analisis Probabilitas Fitur Kategorik
for col in cat_cols:
  plt.figure(figsize=(8,4))

  churn_prob = df.groupby(col)['Churn'].mean().reset_index()
  churn_prob = churn_prob.sort_values(by='Churn', ascending=False)

  sns.barplot(data=churn_prob, x=col, y='Churn', palette='viridis')
  plt.title(f"Probabilitas Chrun berdasarkan {col}")
  plt.ylabel("Probabilitas Churn (0.0 - 1.0)")
  plt.xlabel(col)
  plt.xticks(rotation=45)
  plt.axhline(df['Churn'].mean(), color='red', linestyle='--', label='Rata-rata Churn')
  plt.legend
  plt.tight_layout()
  plt.show()

chi = pd.crosstab(df['MaritalStatus'], df['Churn'])
print(chi)

chi2, p, dof,expected = chi2_contingency(chi)
print(f"P-Value       : {p}")
print("Expected Counts :")
print(expected)

chi_cat = pd.crosstab(df['PreferedOrderCat'], df['Churn'])
print(chi_cat)

chi2, p, dof, expected = chi2_contingency(chi_cat)
print(f"P-Value       : {p}")
print("Expected Counts:")
print(expected)

#Analisis Fitur numerik
num_cols = df.select_dtypes(include=['int64', 'float64']).columns.tolist()
if 'Churn' in num_cols:
  num_cols.remove('Churn')

test_result = []
for col in num_cols:
  group0 = df[df['Churn'] == 0][col].dropna()
  group1 = df[df['Churn'] == 1][col].dropna()

  stat, pval = mannwhitneyu(group0,group1)
  test_result.append({'feature': col, 'p_value': pval})

test_df = pd.DataFrame(test_result).sort_values('p_value')
test_df

"""# **MODELING**


"""

'''New Feature'''
#Interaksi antara Tenure dan Complain
df['Tenure_Complain_Interaction'] = df['Tenure'] * df['Complain']

#Rasio Cashback terhadap Tenure (+1 untuk menghindari pembagian dengan nol)
df['Cashback_per_Tenure'] = df['CashbackAmount'] / (df['Tenure'] + 1)

#Gabungkan kategori yang nilai SHAP-nya mendekati 0 menjadi satu kelompok label baru
kategori_lemah = ['Grocery', 'Others', 'Mobile Phone']
df['PreferedOrderCat'] = df['PreferedOrderCat'].replace(kategori_lemah, 'Other_Product')

df.head(5)

feature = df.drop(columns='Churn')
target= df['Churn']

X_train, X_test, y_train, y_test = train_test_split(feature,
                                                    target,
                                                    test_size = 0.2105,
                                                    stratify = target,
                                                    random_state = 20)

print(f'Training Data features: {X_train.shape}')
print(f'Training Data Target: {y_train.shape}')

categorical_cols = ['PreferedOrderCat', 'MaritalStatus']
num_cols = [c for c in feature.columns if c not in categorical_cols]
preprocessor = ColumnTransformer(
    transformers=[
        ('one hot', OneHotEncoder(handle_unknown='ignore', drop='first'), categorical_cols)
    ],
    remainder='passthrough'
)

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=20)
scoring = ['accuracy','precision', 'recall', 'f1']

def get_optimal_threshold(y_true, y_pred_proba, recall_min=0.80, gap_min=0.15, gap_max=0.25):
  precision, recall, threshold = precision_recall_curve(y_true, y_pred_proba)
  pr_df = pd.DataFrame({
      'Threshold': threshold,
      'Precision': precision[:-1],
      'Recall': recall[:-1]
  })

  pr_df['Gap'] = pr_df['Recall'] - pr_df['Precision']
  valid_thres = pr_df[(pr_df['Gap'] >= gap_min) & (pr_df['Gap'] <= gap_max) & (pr_df['Recall'] >= recall_min)].copy()

  if not valid_thres.empty:
    best_row = valid_thres.sort_values('Precision', ascending=False).iloc[0]
    best_thres = best_row['Threshold']
    print(f"Threshold Optimal: {best_thres:.4f}")
    print(f"Recall: {best_row['Recall']:.3f}, Precision: {best_row['Precision']:.3f}, Gap: {best_row['Gap']:.3f}")
    return best_thres, pr_df
  else:
    print(f"Tidak ditemukan threshold yanag memenuhi syarat (Gap <= {gap_max} & Recall >= {recall_min})")
    print("Menggunakan  threshold: 0.47")
    return 0.47, pr_df

result = pd.concat([y_test.iloc[:10], X_test.iloc[:10]], axis=1)

"""#KNN"""

#Base Model
pipeline_base_knn = Pipeline([
    ('preprocessor', preprocessor),
    ('imputer',KNNImputer()),
    ('oversampling',SMOTETomek(random_state=20)),
    ('model', KNeighborsClassifier())
])

knn_base = cross_validate(pipeline_base_knn, X_train, y_train, cv=cv, scoring=scoring)
knn_base_folds = {'Folds': range(1,6)}

for metric in scoring:
  col_knn_base = f"KNN Base {metric.capitalize()}"
  knn_base_folds[col_knn_base] = knn_base[f'test_{metric}']

result_base_knn = pd.DataFrame(knn_base_folds)
display(result_base_knn.round(4))
display(result_base_knn.mean().round(2))

#Hyperparameter Tuning
knn_params = {
    'model__n_neighbors': [15, 21, 31],
    'model__weights': ['distance'],
    'model__metric': ['manhattan']
}

random_search_knn = RandomizedSearchCV(
    estimator=pipeline_base_knn,
    param_distributions=knn_params,
    n_iter=50,
    scoring='average_precision',
    cv=cv,
    verbose=1,
    random_state=20,
    n_jobs=-1
)

random_search_knn.fit(X_train, y_train)
knn_best_model = random_search_knn.best_estimator_
print(f"Parameter Terbaik: {random_search_knn.best_params_}")

#Threshold Optimization
y_train_pred_proba_knn = cross_val_predict(
    knn_best_model,
    X_train,
    y_train,
    cv=cv,
    method='predict_proba',
    n_jobs=-1
)[:,1]

knn_optimal_thres, pr_df_knn = get_optimal_threshold(y_train, y_train_pred_proba_knn)

#Matrix Evaluation Data Train
pipeline_base_knn.fit(X_train, y_train)
y_test_pred_base_knn = pipeline_base_knn.predict(X_test)

#Matrix Evaluation Data Test
y_test_pred_proba_knn = knn_best_model.predict_proba(X_test)[:,1]
y_test_pred_costum_knn = (y_test_pred_proba_knn >= knn_optimal_thres).astype(int)

print("=====SEBELUM TUNING & THRESHOLD=====")
print(confusion_matrix(y_test, y_test_pred_base_knn))
print(classification_report(y_test, y_test_pred_base_knn))

print("=====SETELAH TUNING & THRESHOLD=====")
print(confusion_matrix(y_test, y_test_pred_costum_knn))
print(classification_report(y_test, y_test_pred_costum_knn))

result['Churn_pred'] = y_test_pred_costum_knn[:10]
result

"""#Support Vector Machine (SVM)"""

#Base Model
pipeline_base_svm = Pipeline([
    ('preprocessor', preprocessor),
    ('imputer',KNNImputer()),
    ('oversampling', SMOTETomek(random_state=20)),
    ('model', SVC(probability=True,random_state=20))
])

svm_base = cross_validate(pipeline_base_svm, X_train, y_train, cv=cv, scoring=scoring)
svm_base_folds = {'Folds': range(1,6)}
for metric in scoring:
  col_svm_base = f"SVM Base {metric.capitalize()}"
  svm_base_folds[col_svm_base] = svm_base[f'test_{metric}']
result_svm_base = pd.DataFrame(svm_base_folds)
display(result_svm_base.round(4))
display(result_svm_base.mean().round(2))

#Hyperparameter Tuning
svm_params = {
    'model__C': [1, 10, 20],
    'model__gamma': ['scale', 0.01],
    'model__kernel': ['rbf']
}

random_search_svm = RandomizedSearchCV(
    estimator=pipeline_base_svm,
    param_distributions=svm_params,
    n_iter=50,
    scoring='average_precision',
    cv=cv,
    verbose=1,
    random_state=20,
    n_jobs=-1
)

random_search_svm.fit(X_train, y_train)
svm_best_model = random_search_svm.best_estimator_
print(f"Parameter Terbaik: {random_search_svm.best_params_}")

#Threshold Optimization
y_train_pred_proba_svm = cross_val_predict(
    svm_best_model,
    X_train,
    y_train,
    cv=cv,
    method='predict_proba',
    n_jobs=-1
)[:,1]

svm_optimal_thres, pr_df_svm = get_optimal_threshold(y_train, y_train_pred_proba_svm)

#Matrix Evaluation Data Train
pipeline_base_svm.fit(X_train, y_train)
y_test_pred_base_svm = pipeline_base_svm.predict(X_test)

#Matrix Evaluation Data test
y_test_pred_proba_svm = svm_best_model.predict_proba(X_test)[:,1]
y_test_pred_costum_svm = (y_test_pred_proba_svm >= svm_optimal_thres).astype(int)

print("=====SEBELUM TUNING & THRESHOLD=====")
print(confusion_matrix(y_test, y_test_pred_base_svm))
print(classification_report(y_test, y_test_pred_base_svm))

print("=====SETELAH TUNING & THRESHOLD=====")
print(confusion_matrix(y_test, y_test_pred_costum_svm))
print(classification_report(y_test, y_test_pred_costum_svm))

result['Churn_pred'] = y_test_pred_costum_svm[:10]
result

"""#Logistic Regression

"""

#Base Model
pipeline_base_logres = Pipeline([
    ('preprocessor', preprocessor),
    ('imputer',KNNImputer()),
    ('oversampling',SMOTETomek(random_state=20)),
    ('model', LogisticRegression(random_state=20))
])

logres_base = cross_validate(pipeline_base_logres, X_train, y_train, cv=cv, scoring=scoring)
logres_base_folds = {'Folds': range(1,6)}
for metric in scoring:
  col_logres_base = f"Logres Base {metric.capitalize()}"
  logres_base_folds[col_logres_base] = logres_base[f'test_{metric}']

result_base_logres = pd.DataFrame(logres_base_folds)
display(result_base_logres.round(4))
display(result_base_logres.mean().round(2))

#Hyperparameter Tuning
logres_params = {
    'model__C': [0.1, 1, 10],
    'model__penalty': ['l2'],
    'model__solver': ['lbfgs', 'liblinear']
}

random_search_logres = RandomizedSearchCV(
    estimator=pipeline_base_logres,
    param_distributions=logres_params,
    n_iter=50,
    scoring='average_precision',
    cv=cv,
    verbose=1,
    random_state=20,
    n_jobs=-1
)

random_search_logres.fit(X_train, y_train)
logres_best_model = random_search_logres.best_estimator_
print(f"Parameter Terbaik: {random_search_logres.best_params_}")

#Threshold Optimization
y_train_pred_proba_logres = cross_val_predict(
    logres_best_model,
    X_train,
    y_train,
    cv=cv,
    method='predict_proba',
    n_jobs=-1
)[:,1]

logres_optimal_thres, pr_df_logres = get_optimal_threshold(y_train, y_train_pred_proba_logres)

#Matrix Evaluation Data Train
pipeline_base_logres.fit(X_train, y_train)
y_test_pred_base_logres = pipeline_base_logres.predict(X_test)

#Matrix Evaluation Data Test
y_test_pred_proba_logres = logres_best_model.predict_proba(X_test)[:,1]
y_test_pred_costum_logres = (y_test_pred_proba_logres >= logres_optimal_thres).astype(int)

print("=====SEBELUM TUNING & THRESHOLD=====")
print(confusion_matrix(y_test, y_test_pred_base_logres))
print(classification_report(y_test, y_test_pred_base_logres))

print("=====SETELAH TUNING & THRESHOLD=====")
print(confusion_matrix(y_test,y_test_pred_costum_logres))
print(classification_report(y_test,y_test_pred_costum_logres))

result['Churn_pred'] = y_test_pred_costum_logres[:10]
result

"""#Random Forest

"""

#Base Model
pipeline_base_rf = Pipeline([
    ('preprocessor', preprocessor),
    ('imputer', KNNImputer()),
    ('oversampling',SMOTETomek(random_state=20)),
    ('model', RandomForestClassifier(random_state=20))
])

rf_base = cross_validate(pipeline_base_rf, X_train, y_train, cv=cv, scoring=scoring)

rf_base_folds = {'Folds': range(1,6)}
for metric in scoring:
  col_rf_base = f"RF Base {metric.capitalize()}"
  rf_base_folds[col_rf_base] = rf_base[f'test_{metric}']

result_rf_base = pd.DataFrame(rf_base_folds)
display(result_rf_base.round(4))
display(result_rf_base.mean().round(2))

#Hyperparameter Tuning
rf_params = {

    'model__n_estimators': [200],
    'model__max_depth': [5, 7],
    'model__min_samples_leaf': [30, 50],
    'model__max_features': ['sqrt']
}

random_search_rf = RandomizedSearchCV(
    estimator=pipeline_base_rf,
    param_distributions=rf_params,
    n_iter=50,
    scoring='average_precision',
    cv=cv,
    random_state=20,
    n_jobs=-1
)

random_search_rf.fit(X_train, y_train)
rf_best_model = random_search_rf.best_estimator_
print(f"Parameter Terbaik: {random_search_rf.best_params_}")

#Threshold Optimization
y_train_pred_proba_rf = cross_val_predict(
    rf_best_model,
    X_train,
    y_train,
    cv=cv,
    method='predict_proba',
    n_jobs=-1
)[:,1]

rf_optimal_thres, pr_df_rf = get_optimal_threshold(y_train, y_train_pred_proba_rf)

#Matrix Evaluation Data Train
pipeline_base_rf.fit(X_train, y_train)
y_test_pred_base_rf = pipeline_base_rf.predict(X_test)

#Matrix Evaluation Data Test
y_test_pred_proba_rf = rf_best_model.predict_proba(X_test)[:,1]
y_test_pred_costum_rf = (y_test_pred_proba_rf >= rf_optimal_thres).astype(int)

print("=====SEBELUM TUNING & THRESHOLD=====")
print(confusion_matrix(y_test, y_test_pred_base_rf))
print(classification_report(y_test, y_test_pred_base_rf))

print("=====SETELAH TUNING & THRESHOLD=====")
print(confusion_matrix(y_test,y_test_pred_costum_rf))
print(classification_report(y_test,y_test_pred_costum_rf))

result = pd.concat([y_test.iloc[:10], X_test.iloc[:10]], axis=1)
result['Churn_pred'] = y_test_pred_costum_rf[:10]
result

"""#XGBoost"""

#Base Model XGB
ratio = y_train.value_counts()[0] / y_train.value_counts()[1]

pipeline_base_xgb = Pipeline([
    ('preprocessor', preprocessor),
    ('imputer', KNNImputer()),
    ('oversampling', SMOTETomek(random_state=20)),
    ('model', XGBClassifier(random_state=20))
])

xgb_base = cross_validate(pipeline_base_xgb, X_train, y_train, cv=cv, scoring=scoring)

xgb_base_folds = {'Folds': range(1,6)}
for metric in scoring:
  col_xgb_base = f"XGB Base {metric.capitalize()}"
  xgb_base_folds[col_xgb_base] = xgb_base[f'test_{metric}']

result_xgb_base = pd.DataFrame(xgb_base_folds)
display(result_xgb_base.round(4))
display(result_xgb_base.mean().round(2))

#Hyperparameter Tuning
xgb_params = {
    'model__max_depth': [3, 4],
    'model__learning_rate': [0.01, 0.05],
    'model__reg_alpha': [1, 10],
    'model__reg_lambda': [5, 20],
    'model__subsample': [0.6, 0.7],
    'model__colsample_bytree': [0.6, 0.7]
}

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=20)

random_search_xgb = RandomizedSearchCV(
    estimator=pipeline_base_xgb,
    param_distributions=xgb_params,
    n_iter=50,
    scoring='average_precision',
    cv=cv,
    verbose=1,
    random_state=20,
    n_jobs=-1
)

random_search_xgb.fit(X_train, y_train)
xgb_best_model = random_search_xgb.best_estimator_
print(f"\nParameter Terbaik: {random_search_xgb.best_params_}")

#Threshold Optimization
y_train_pred_proba = cross_val_predict(
    xgb_best_model,
    X_train,
    y_train,
    cv=cv,
    method='predict_proba',
    n_jobs=-1
)[:,1]

xgb_optimal_thres, pr_df_xgb = get_optimal_threshold(y_train, y_train_pred_proba)

#Matrix Evaluation Data Train
pipeline_base_xgb.fit(X_train, y_train)
y_test_pred_base_xgb = pipeline_base_xgb.predict(X_test)

#Matrix Evaluation Data Test
y_test_pred_proba_xgb = xgb_best_model.predict_proba(X_test)[:,1]
y_test_pred_costum_xgb = (y_test_pred_proba_xgb >= xgb_optimal_thres).astype(int)

print("=====SEBELUM TUNING & THRESHOLD=====")
print(confusion_matrix(y_test, y_test_pred_base_xgb))
print(classification_report(y_test, y_test_pred_base_xgb))

print("=====SETELAH TUNING & THRESHOLD=====")
print(confusion_matrix(y_test, y_test_pred_costum_xgb))
print(classification_report(y_test, y_test_pred_costum_xgb))

result['Churn_pred'] = y_test_pred_costum_xgb[:10]
result

"""# SOFT VOTING

"""

voting_clf = VotingClassifier(
    estimators=[
        ('rf', rf_best_model),
        ('xgb', xgb_best_model),
        ('logres', logres_best_model),
    ],
    voting='soft',
    weights=[3, 3,1],
    n_jobs=-1
)

voting_cv = cross_validate(voting_clf, X_train, y_train, cv=cv, scoring=scoring)
voting_folds = {'Folds': range(1,6)}
for metric in scoring:
  voting_folds[f"Voting {metric.capitalize()}"] = voting_cv[f'test_{metric}']
display(pd.DataFrame(voting_folds).round(4))
display(pd.DataFrame(voting_folds).mean().round(2))

#Threshold Optimization
voting_clf.fit(X_train, y_train)
y_train_pred_proba_voting = cross_val_predict(
    voting_clf,
    X_train,
    y_train,
    cv=cv,
    method='predict_proba',
    n_jobs=-1
)[:,1]

voting_optimal_thres, pr_df_voting = get_optimal_threshold(y_train, y_train_pred_proba_voting)

y_test_pred_proba_voting = voting_clf.predict_proba(X_test)[:,1]
y_test_pred_costum_voting = (y_test_pred_proba_voting >= voting_optimal_thres).astype(int)

print("=====VOTING (RF+XGB+LogReg) SESUDAH THRESHOLD=====")
print(confusion_matrix(y_test, y_test_pred_costum_voting))
print(classification_report(y_test, y_test_pred_costum_voting))

result['Churn_pred'] = y_test_pred_costum_voting[:10]
result

"""#Comparing Tuned & Threshold Model

"""

models_results = {
    'KNN': y_test_pred_costum_knn,
    'Logistic Regression': y_test_pred_costum_logres,
    'SVM': y_test_pred_costum_svm,
    'Random Forest': y_test_pred_costum_rf,
    'XGBoost': y_test_pred_costum_xgb,
    'Soft Voting': y_test_pred_costum_voting
}

thresholds_used = {
    'KNN': knn_optimal_thres,
    'Logistic Regression': logres_optimal_thres,
    'SVM': svm_optimal_thres,
    'Random Forest': rf_optimal_thres,
    'XGBoost': xgb_optimal_thres,
    'Soft Voting': voting_optimal_thres
}

comparison = []
for name, y_pred in models_results.items():
    rec = recall_score(y_test, y_pred)
    prec = precision_score(y_test, y_pred)
    acc = accuracy_score(y_test, y_pred)
    gap = abs(rec - prec)
    comparison.append({
        'Model': name,
        'Threshold': round(thresholds_used[name], 4),
        'Recall': round(rec, 3),
        'Precision': round(prec, 3),
        'Gap': round(gap, 3),
        'Accuracy': round(acc, 3),
        'Memenuhi_Target (Recall>=0.80 & Gap<=0.20)': (rec >= 0.80) and (gap <= 0.20)
    })

comparison_df = pd.DataFrame(comparison).sort_values('Recall', ascending=False).reset_index(drop=True)
display(comparison_df)

"""#Catatan
###"Meski XGBoost tunggal memenuhi target gap secara ketat, saat divalidasi lebih lanjut pada test set berlabel dan simulasi prediksi tanpa label, Soft Voting menunjukkan hasil yang lebih konsisten/stabil, sehingga dipilih sebagai model final meski gap-nya sedikit di atas target pada train test."

#Confusion Matrix Final Model (Soft Voting)
"""

cm_before = confusion_matrix(y_test, y_test_pred_base_xgb)
cm_after = confusion_matrix(y_test, y_test_pred_costum_voting)
fig, axes = plt.subplots(1, 2, figsize=(12, 5))

sns.heatmap(cm_before, annot=True, fmt='d', cmap='Blues', ax=axes[0])
axes[0].set_title('Tuning + Threshold (XGBoost - Default 0.47)')
axes[0].set_xlabel('Predicted')
axes[0].set_ylabel('Actual')

sns.heatmap(cm_after, annot=True, fmt='d', cmap='Greens', ax=axes[1])
axes[1].set_title(f'Sesudah Threshold (Soft Voting - {voting_optimal_thres:.2f})')
axes[1].set_xlabel('Predicted')
axes[1].set_ylabel('Actual')

plt.tight_layout()
plt.show()

"""#ROC Curve"""

y_test_proba_voting = voting_clf.predict_proba(X_test)[:, 1]
auc_score = roc_auc_score(y_test, y_test_proba_voting)

RocCurveDisplay.from_predictions(y_test, y_test_proba_voting)
plt.plot([0, 1], [0, 1], linestyle='--', color='gray', label='Random Guess')
plt.title(f"ROC Curve Soft Voting (AUC = {auc_score:.3f})")
plt.legend()
plt.show()

"""#Precision Recall Curve

"""

ap_score = average_precision_score(y_test, y_test_proba_voting)
prec_score = precision_score(y_test, y_test_pred_costum_voting)
rec_score = recall_score(y_test, y_test_pred_costum_voting)

PrecisionRecallDisplay.from_predictions(y_test, y_test_proba_voting)
plt.scatter(rec_score, prec_score, color='red', s=100,  zorder=5, label=f'Threshold Terpilih {voting_optimal_thres:.2f}')
plt.title(f'Precision Recall Curve Soft Voting (AP = {ap_score:.3f})')
plt.legend()
plt.show()

"""#Learning Curve"""

train_sizes, train_score, val_score = learning_curve(
    voting_clf, X_train, y_train, cv=cv, scoring='accuracy',
    train_sizes=np.linspace(0.1, 1.0, 6), n_jobs=-1
)

plt.figure(figsize=(8,5))
plt.plot(train_sizes, train_score.mean(axis=1), 'o-', label='Train Score')
plt.plot(train_sizes, val_score.mean(axis=1), 'o-', label='Validation Score')
plt.xlabel('Jumlah Data Training')
plt.ylabel('Accuracy')
plt.title('Learning Curve (Accuracy) - Soft Voting')
plt.legend()
plt.grid(alpha=0.3)
plt.show()

train_sizes, train_score, val_score = learning_curve(
   voting_clf, X_train, y_train, cv=cv, scoring='recall',
    train_sizes=np.linspace(0.1, 1.0, 6), n_jobs=-1
)

plt.figure(figsize=(8,5))
plt.plot(train_sizes, train_score.mean(axis=1), 'o-', label='Train Score')
plt.plot(train_sizes, val_score.mean(axis=1), 'o-', label='Validation Score')
plt.xlabel('Jumlah Data Training')
plt.ylabel('Recall')
plt.title('Learning Curve (Recall) - Soft Voting')
plt.legend()
plt.grid(alpha=0.3)
plt.show()

"""#Feature Importance & SHAP

"""

ohe_cols = preprocessor.named_transformers_['one hot'].get_feature_names_out(categorical_cols)
remainder_cols = [c for c in feature.columns if c not in categorical_cols]
all_cols = list(ohe_cols) + remainder_cols

voting_pipeline = voting_clf.named_estimators_['xgb']
voting_model = voting_pipeline.named_steps['model']

#Ekstrak feature importance
importances = voting_model.feature_importances_

feat_imp_df = pd.DataFrame({
    'Feature': all_cols,
    'Importance': importances
}).sort_values('Importance', ascending=False).reset_index(drop=True)

display(feat_imp_df)

plt.figure(figsize=(9, 6))
plt.barh(feat_imp_df['Feature'][::-1], feat_imp_df['Importance'][::-1])
plt.xlabel('Importance')
plt.title('Feature Importance - Soft Voting (Final Model)')
plt.tight_layout()
plt.show()

X_test_transformed = preprocessor.transform(X_test)

#Ambil pipeline XGBoost dari dalam VotingClassifier yang sudah di-fit
xgb_pipeline_fitted = voting_clf.named_estimators_['xgb']
model_xgb_raw = xgb_pipeline_fitted.named_steps['model']

#Inisialisasi TreeExplainer dengan model XGBoost
explainer = shap.TreeExplainer(model_xgb_raw)
shap_values = explainer(X_test_transformed)

feature_names = preprocessor.get_feature_names_out()
X_test_transformed_df = pd.DataFrame(X_test_transformed, columns=feature_names)
X_test_transformed_df.columns = X_test_transformed_df.columns.str.replace('one hot__', '', regex=False)
X_test_transformed_df.columns = X_test_transformed_df.columns.str.replace('remainder__', '', regex=False)

if len(shap_values.shape) == 3:
    shap_values_to_plot = shap_values[:, :, 1]
else:
    shap_values_to_plot = shap_values

plt.figure(figsize=(10, 8))
shap.summary_plot(shap_values_to_plot, X_test_transformed_df, show=False)
plt.subplots_adjust(left=0.35)
plt.title('SHAP Summary Plot - XGBoost (Extracted from Voting)')
plt.show()

"""#Saving Final Model"""

model_filename = 'soft_final_model2.pkl'
with open(model_filename, 'wb') as file:
    pickle.dump(voting_clf, file)

print(f"Model berhasil disimpan dengan nama: {model_filename}")