# -*- coding: utf-8 -*-
"""Testing_Model_Capstone_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ExL9-OcIXZDgCK7kOUvpkF75zmBJ9QQs
"""

from google.colab import drive
import pandas as pd
import pickle
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.ensemble import RandomForestClassifier, VotingClassifier
from sklearn.linear_model import LogisticRegression
from xgboost import XGBClassifier
from sklearn.datasets import make_classification

"""#Soft Voting Testing Final Model

"""

drive.mount('/content/drive')
path = '/content/drive/MyDrive/Dataset Capstone 3/'
model_path = path + 'soft_final_model2.pkl'
test_path = path + 'data_test_5.csv'
df_test = pd.read_csv(test_path)

df_test.info()

df_test['PreferedOrderCat'] = df_test['PreferedOrderCat'].replace({'Mobile': 'Mobile Phone'})
KATEGORI_LEMAH = ['Grocery', 'Others', 'Mobile Phone']
df_test['PreferedOrderCat'] = df_test['PreferedOrderCat'].replace(KATEGORI_LEMAH, 'Other_Product')
df_test['Tenure_Complain_Interaction'] = df_test['Tenure'] * df_test['Complain']
df_test['Cashback_per_Tenure'] = df_test['CashbackAmount'] / (df_test['Tenure'] + 1)

X_test = df_test.drop(columns='Churn')
y_test = df_test['Churn']
cat_cols = X_test.select_dtypes(include=['object']).columns


with open(model_path, 'rb') as f:
    soft_voting_model = pickle.load(f)

import warnings
THRESHOLD = 0.47
with warnings.catch_warnings():
    warnings.filterwarnings("ignore", category=UserWarning, message=".*unknown categories.*")
    y_pred_proba = soft_voting_model.predict_proba(X_test)[:, 1]
    y_pred = (y_pred_proba >= THRESHOLD).astype(int)


print(f"Model Loaded: {model_path.split('/')[-1]}")
print("Soft Voting Model Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

# Visualisasi Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
plt.figure(figsize=(8,6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('Confusion Matrix Soft Voting (Testing)')
plt.show()

"""# Testing Tanpa Label (Y)

"""

df_new = pd.read_csv(test_path).drop(columns=['Churn'], errors='ignore')

# 2. FEATURE ENGINEERING
df_new['Tenure_Complain_Interaction'] = df_new['Tenure'] * df_new['Complain']
df_new['Cashback_per_Tenure'] = df_new['CashbackAmount'] / (df_new['Tenure'] + 1)

cat_cols = df_new.select_dtypes(include=['object']).columns
df_new[cat_cols] = df_new[cat_cols].fillna('Unknown').astype(str)


with warnings.catch_warnings():
    warnings.filterwarnings("ignore", category=UserWarning)
    predictions = soft_voting_model.predict(df_new)
    probabilities = soft_voting_model.predict_proba(df_new)[:, 1] # Probabilitas Churn (Kelas 1)


df_new['Prediction'] = predictions
df_new['Churn_Probability'] = probabilities
display(df_new[['Tenure', 'Complain', 'Prediction', 'Churn_Probability']].head())
print(f"\nTotal data yang diprediksi: {len(df_new)}")

fig, ax = plt.subplots(1, 2, figsize=(15, 5))

# Distribusi Probabilitas
sns.histplot(df_new['Churn_Probability'], bins=20, kde=True, ax=ax[0], color='purple')
ax[0].set_title('Distribusi Probabilitas Churn')
ax[0].set_xlabel('Probabilitas')
ax[0].axvline(0.47, color='red', linestyle='--', label='Threshold (0.47)')
ax[0].legend()

# Perbandingan Jumlah Prediksi
sns.countplot(x='Prediction', data=df_new, ax=ax[1], palette='viridis')
ax[1].set_title('Jumlah Prediksi: Tetap (0) vs Churn (1)')
ax[1].set_xticklabels(['Tetap (0)', 'Churn (1)'])

plt.tight_layout()
plt.show()

# Top 5 pelanggan probabilitas churn TERTINGGI (paling berisiko churn)
print("\nTop 5 Pelanggan Dengan Probabilitas Tertinggi Melakukan Churn:")
display(df_new.sort_values(by='Churn_Probability', ascending=False).head())

# Top 5 pelanggan probabilitas churn TERENDAH (paling yakin tetap aktif)
print("\nTop 5 Pelanggan Dengan Probabilitas Terendah Melakukan Churn (Paling Yakin Tetap):")
display(df_new[df_new['Prediction'] == 0].sort_values(by='Churn_Probability', ascending=True).head())

import shap

# Ambil pipeline XGBoost yang sudah di-fit dari dalam VotingClassifier
xgb_pipeline_fitted = soft_voting_model.named_estimators_['xgb']
preprocessor_fitted = xgb_pipeline_fitted.named_steps['preprocessor']
model_xgb_raw = xgb_pipeline_fitted.named_steps['model']

# Transform X_test (data test asli dari data_test_5.csv), JANGAN fit ulang
X_test_transformed = preprocessor_fitted.transform(X_test)

# Kalau hasil transform sparse matrix, ubah ke dense
if hasattr(X_test_transformed, "toarray"):
    X_test_transformed = X_test_transformed.toarray()

feature_names = preprocessor_fitted.get_feature_names_out()
X_test_transformed_df = pd.DataFrame(X_test_transformed, columns=feature_names)
X_test_transformed_df.columns = X_test_transformed_df.columns.str.replace('one hot__', '', regex=False)
X_test_transformed_df.columns = X_test_transformed_df.columns.str.replace('remainder__', '', regex=False)

# Inisialisasi TreeExplainer dengan model XGBoost hasil ekstraksi
explainer = shap.TreeExplainer(model_xgb_raw)
shap_values = explainer(X_test_transformed_df)

# Untuk klasifikasi biner, ambil kelas 1 (Churn) kalau output 3 dimensi
if len(shap_values.shape) == 3:
    shap_values_to_plot = shap_values[:, :, 1]
else:
    shap_values_to_plot = shap_values

plt.figure(figsize=(10, 8))
shap.summary_plot(shap_values_to_plot, X_test_transformed_df, show=False)
plt.subplots_adjust(left=0.35)
plt.title('SHAP Summary Plot - XGBoost (Extracted from Soft Voting)')
plt.show()